### PR TITLE
Additional Brazilian area codes

### PR DESCRIPTION
**Pull request by ZeeCoder**
We've noticed that in Brazil, some phone numbers cannot be formatted.

After looking at wikipedia, I've found a number of area codes missing:
https://en.wikipedia.org/wiki/List_of_dialling_codes_in_Brazil#/media/File:Brasil_-_C%C3%B3digos_de_%C3%A1rea_DDD.png

I've added those.

Also, I've removed two tests, that seem to be valid and cannot find any references as to why those should not be valid cases.

Not sure if you could advise on those?

### CODE REVIEW

**Comment by Bossa573** [comment]
As there are much more area codes being added to the list, 
can you verify if this big difference is because the newly added area codes do not belong to the mobile phone?

Because this module is focusing on the mobile phone number at the moment, 
I cannot tell some codes (such as `11` to `19`) are missing due to this reason/

**Comment by ZeeCoder** [comment]
Hmm haven't checked that, I'll need to do some googling, some might not be for mobile phones.

**Comment by teddychan** [comment]
Just remind that this phone lib is mainly to detect if a `phone number` is a `mobile number`, mainly for sending out the SMS.

If we cannot tell if the phone number is a mobile, we prefer not to include it first.

For some SMS providers, sending out an SMS cost $$ even the number is not a valid mobile number

**Comment by Bossa573** [comment]
closing this PR due to inactivity
please reopen the PR if you can provide any new documentation illustrating the mobile phone number usage of these area codes

**Comment by liviopv** [comment]
> can you verify if this big difference is because the newly added area codes do not belong to the mobile phone?

@Bossa573 @ZeeCoder @teddychan all area codes in Brazil are used for mobile phone numbers, including the ones in this PR.

In the link below, there's a table with recent stats of the number of mobile phones per area code in Brazil in thousands (for instance, the `11` area code has 35.574, which represents 35574000 active phone numbers in August 2019):

https://www.teleco.com.br/ncelddd.asp 

Teleco is one of the major telecommunications consulting firms in Brazil, it's one of the most trusted sources for this type of information.

With that in mind, can we reopen and merge this PR?

**Comment by Bossa573** [comment]
@liviopv sure I'll reopen the PR and reevaluate as related references are provided, thanks for the contribution

**Comment by Bossa573** [comment]
https://github.com/AfterShip/phone/releases/tag/2.3.22

**Comment by akirk** [comment]
Great, thank you for the quick merge and release!

**Pull request merged**
