### PR TITLE
Norbertkeri/update hk phone

### PR DESCRIPTION
**Pull request by RSSNorbertKeri**

### CODE REVIEW

**Comment by Bossa573** [comment]
hello @RSSNorbertKeri 
thanks for the PR, some questions:
1. can you include any references? websites or docs
2. for `81`, `82`, `83`, `84`, `85`, `86`, `87`, `88`, `89`, can't it be generalized into `8`?

**Comment by Bossa573** [comment]
and 3. what is the usage of newly added module `webpack-sources` in `package.json`?

**Comment by RSSNorbertKeri** [comment]
Hello @Bossa573 ,

Thanks for the questions.
First, I work with Hong Kong team and they requested this change.

1. For reference I found this one:
https://en.wikipedia.org/wiki/Telephone_numbers_in_Hong_Kong
2. No, we can't it be generalized into 8, because 80 isn't included into list.
3. I had issue with "babel-minify-webpack-plugin" when I tried to build.
I found a solution in this comment:
https://github.com/webpack-contrib/babel-minify-webpack-plugin/issues/68#issuecomment-352193013
You can ignore/remove this line if you can build successfully.

**Comment by Bossa573** [comment]
@RSSNorbertKeri 

Thanks for the info,

1. I've also verified against the hong kong government article:
https://www.info.gov.hk/gia/general/201802/05/P2018020500302.htm
should be correct

2. I see, didn't notice that `80` is not supported

3. noted, I'll keep that under devDependency

Thanks for the information and will publish the changes soon.

(by the way, didn't notice that the new mobile phone number has been rolled out even I'm hong kong people LOL)

**Comment by Bossa573** [comment]
https://github.com/AfterShip/phone/releases/tag/2.3.9

**Comment by RSSNorbertKeri** [comment]
Thanks @Bossa573

**Pull request merged**
