### PR TITLE
feat: add xk to phone data

### PR DESCRIPTION
**Pull request by alekangelov**
Hey, Kosovo is missing from the phone data, I added it + added a test for it. They have 6 mobile prefixes and the length of their mobile numbers is 8.

sources:

https://www.howtocallabroad.com/kosovo/
https://en.wikipedia.org/wiki/Telephone_numbers_in_Kosovo

The number format is 04x xxx xxx which is 8 digits.

Cheers

### CODE REVIEW

**Comment by DionIslami1** [comment]
This would be great help, great job @alekangelov 🚀🚀

**Review by DionIslami1 — APPROVED** [review]

**Comment by Bossa573** [comment]
@alekangelov hello, please provide docs / website / wiki showing that Kosovo's **mobile** phone number format, thanks

**Comment by alekangelov** [comment]
@Bossa573 Should I add as comment in code or just reference here? Cheers

**Comment by alekangelov** [comment]
added references to code as well cheers

**Comment by Bossa573** [comment]
@alekangelov the code is optional though. adding in github ticket is enough, coz it's only for manual reviewing

**Comment by alekangelov** [comment]
just in case :+1:

**Review by Bossa573 — APPROVED** [review]

**Comment by Bossa573** [comment]
https://www.npmjs.com/package/phone/v/3.1.45

it's out

**Comment by Bossa573** [comment]
https://github.com/AfterShip/phone/releases/tag/3.1.45

**Comment by alekangelov** [comment]
sick cheers

**Pull request merged**
