### PR TITLE
Accept GBR 9 digit landline numbers

### PR DESCRIPTION
**Pull request by LukaszWiktor**
According to Wikipedia, there are some 9 digit landline numbers that are valid in the UK/GBR.

Source: https://en.wikipedia.org/wiki/Telephone_numbers_in_the_United_Kingdom

### CODE REVIEW

**Comment by LukaszWiktor** [comment]
I came across such a number in production env.

**Comment by Bossa573** [comment]
the library is not intended to support any kind of landline phone number validation.
please reopen the if you find such case for `mobile` phone numbers

**Comment by LukaszWiktor** [comment]
too bad

**Comment by LukaszWiktor** [comment]
I assumed that setting the `validateMobilePrefix` parameter to `false` would enable me to validate landline numbers. Actually, I don't need the validation part, I only need a library to normalize/format phone numbers according to the E.164 standard. Do you know if such a library exists?

**Comment by Bossa573** [comment]
sorry I don't have an alternative option for your use case

**Pull request closed without merging**
