### PR TITLE
Extend nigeria format to allow 091

### PR DESCRIPTION
**Pull request by papidb**

### CODE REVIEW

**Comment by Bossa573** [comment]
Thanks for the PR and this will be included in the next verrsion

**Comment by papidb** [comment]
Thanks boss. I use this tool extensively and want to help more, how do I do this?

**Comment by Bossa573** [comment]
Thank you for your support, for this module maintenance, most of the update is about the phone data update, and this would mainly rely on community helps (as I'm not actively scanning through all the country one by one and see which is updated)
So if you find any format needs to be updated, simply opening PRs (with related docs / URL / wikis showing the update) would be a big help, thank you very much.

**Comment by Bossa573** [comment]
https://github.com/AfterShip/phone/releases/tag/3.1.6

**Comment by papidb** [comment]
Thanks.

**Pull request merged**
