### PR TITLE
Breaking Change: support partial phone area data

### PR DESCRIPTION
**Pull request by suhaotian**

### CODE REVIEW

**Comment by suhaotian** [comment]
so many change because of vscode auto format

**Comment by Bossa573** [comment]
Thank you for your contribution.

However, we do not have a plan for accepting significant feature changes (especially breaking change) nor minor refactoring other than phone number data issue,
until the next major version bump (version 3)

By the way, a suggestion for your reference,
please separate different things (feature changes, refactoring, linting) into individual PRs.

**Comment by suhaotian** [comment]
Got it. But I only want support just fewer country, I have to publish another npm pacakge...

**Comment by Bossa573** [comment]
Partial country support would be an interesting idea,
would you mind sharing which kind of situation you have so that you need to disable some of the country?

**Comment by Bossa573** [comment]
Some more comment about the PR for your reference:
1. breaking change require a major version bump, please refer to https://semver.org/
2. Set up phone data manually extremely complicated the usability of the module, even set up only once per project.
3. Some of your files are tab-indented, some are space-indented, also some are single-quoted, some are double-quoted, please be consistent.
4. The project is tab-indented, single-quoted (and also in fact, all javascript projects should be single-quoted. Some famous linting rules: https://github.com/airbnb/javascript#strings--quotes), please respect project configuration instead of applying your personal preference.

**Comment by suhaotian** [comment]
> Partial country support would be an interesting idea,
> would you mind sharing which kind of situation you have so that you need to disable some of the country?

Yeah, There are a project that only need support China MainLand, Honk Kong, Taiwan, Macao, so the rest are not need....

**Comment by suhaotian** [comment]
> Some more comment about the PR for your reference:
> 
> 1. breaking change require a major version bump, please refer to https://semver.org/
> 2. Set up phone data manually extremely complicated the usability of the module, even set up only once per project.
> 3. Some of your files are tab-indented, some are space-indented, also some are single-quoted, some are double-quoted, please be consistent.
> 4. The project is tab-indented, single-quoted (and also in fact, all javascript projects should be single-quoted. Some famous linting rules: https://github.com/airbnb/javascript#strings--quotes), please respect project configuration instead of applying your personal preference.
For the 1, ok, I will bump version... but 2, yeah... became a little more complicated
For the 3,4, Can I add a prettier depenciese to autoformat the whole code with git hook?

**Comment by Bossa573** [comment]
1. I mean even you don't need extra countries, do you have any example that "if there are other countries on the list, it will severely affect your use case"?

2. If the only aim for china, HK, TW, Macau:
a) for cleaning up the phone number, you can simply use some regex
b) I assume you have already know which phone numbers belong to which area - because for example if you just input 61234567, the library can not differentiate correctly if it's +852 (HK) or +853 (Macau)
If you have already know the phone number country, then it's easy to implement a helper to prepend +86/852/853/886

**Comment by Bossa573** [comment]
>For the 3,4, Can I add a prettier dependencies to autoformat the whole code with git hook?

No, the point is **You should not change the project's setting to your own preference**

**Comment by suhaotian** [comment]
Thank you for the patient and the good advices.

**Comment by suhaotian** [comment]
> > For the 3,4, Can I add a prettier dependencies to autoformat the whole code with git hook?
> 
> No, the point is **You should not change the project's setting to your own preference**

But prettier is good, why not

**Comment by Bossa573** [comment]
You misunderatand the problem.
If the project is using tab, use tab.
If the project is using space, use space.
Do not change the project preference,
it's not about you want to use prettier or not

**Comment by suhaotian** [comment]
I mean prettier can have configure to use tab and double quotes, https://prettier.io/docs/en/configuration.html

image

**Comment by Bossa573** [comment]
I know prettier can do every configuration, just to emphasize about adopting the project's configuration

**Comment by Bossa573** [comment]
closing the discussion as off topic, however feel free to discuss by creating a new issue if needed

**Pull request closed without merging**
