### PR TITLE
Update for Morocco

### PR DESCRIPTION
**Pull request by Oudmane**
In Morocco, some operators have mobile numbers that starts with 7

### CODE REVIEW

**Comment by Bossa573** [comment]
Hello @Oudmane, can you add any reference data here?

**Comment by Oudmane** [comment]
Hello @Bossa573 Here's the announcement of ANRT(National Agency for the legalization of communications, it's in french)
https://www.anrt.ma/content/plan-national-de-numerotation-un-prefixe-07-supplementaire-pour-la-telephonie-mobile

**Comment by Bossa573** [comment]
@Oudmane Thanks for the information will merge the PR and publish soon

**Comment by Oudmane** [comment]
@Bossa573  Thank you guys for this package :)

**Comment by Bossa573** [comment]
@Oudmane version 2.3.8 has been published, cheers

**Pull request merged**
