### PR TITLE
Update Ukraine `mobile_begin_with`

### PR DESCRIPTION
**Pull request by Kamikadze4GAME**
I'm living in Ukraine and there is full list of number codes of our mobile operators

### CODE REVIEW

**Comment by hans-lizihan** [comment]
@Kamikadze4GAME sorry for the mess, we finally land our v2 branch into master, please kindly help resolve the conflicts, thank you

**Comment by Bossa573** [comment]
Thanks for information, handled in https://github.com/AfterShip/phone/pull/140
Only added `73`, for the rest, please provide related references, thanks

**Comment by Kamikadze4GAME** [comment]
Sorry for delay.
[List of all our codes](https://maanimo.com/helpful/142623-kody-operatorov).

**Comment by Bossa573** [comment]
@Kamikadze4GAME please discuss in https://github.com/AfterShip/phone/issues/142

**Pull request closed without merging**
